ALTER TABLE "Meter"
ADD COLUMN "lowBalanceAlertEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "lowBalanceThreshold" DOUBLE PRECISION NOT NULL DEFAULT 5,
ADD COLUMN "lastLowBalanceAlertAt" TIMESTAMP(3),
ADD COLUMN "autoTopUpEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "autoTopUpThreshold" DOUBLE PRECISION NOT NULL DEFAULT 5,
ADD COLUMN "autoTopUpAmountCents" INTEGER,
ADD COLUMN "autoTopUpPaymentMethod" TEXT NOT NULL DEFAULT 'MPESA',
ADD COLUMN "lastAutoTopUpAt" TIMESTAMP(3);
